export enum ChatEvents {
    CONNECT = 'connect',
    DISCONNECT = 'disconnect',
    START_CONVERSATION= 'START_CONVERSATION',
    JOIN_CHAT = 'joinChat',
    LEAVE_CHAT = 'leaveChat',
    SEND_MESSAGE = 'sendMessage',
    RECEIVE_MESSAGE = 'receiveMessage',
    USER_TYPING = 'userTyping',
    USER_STOP_TYPING = 'userStopTyping',
    MESSAGE_DELIVERED = 'messageDelivered',
    MESSAGE_READ = 'messageRead',
    ERROR = 'ERROR',
    CONVERSATION_CREATED = 'CONVERSATION_CREATED',
    NEW_CONVERSATION = 'NEW_CONVERSATION',
    CONVERSATION_EXISTS= 'CONVERSATION_EXISTS',
    ONLINE_CONTACTS = 'ONLINE_CONTACTS',
    USER_ONLINE = 'USER_ONLINE',
    USER_OFLINE = 'USER_OFLINE'
}